// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  LineCommentTitle = 2,
  Oql = 3,
  Group = 6,
  Query = 7,
  Keyword = 8,
  SquareFilter = 11,
  Tag = 12,
  Regex = 13,
  Identifier = 14,
  Macro = 15,
  MacroValue = 16,
  LanguageCode = 18,
  RoundFilter = 19,
  Assignment = 20,
  Set = 22
